<?php
return array (
  0 => 
  array (
    'typeid' => '55',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '14',
    'name' => '展会模型',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  1 => 
  array (
    'typeid' => '61',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '17',
    'name' => '会议模型',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  2 => 
  array (
    'typeid' => '62',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '19',
    'name' => '外贸知道',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '',
  ),
  3 => 
  array (
    'typeid' => '63',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '20',
    'name' => 'zjsb',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '0',
    'description' => '资金申报',
  ),
  4 => 
  array (
    'typeid' => '1',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '1',
    'name' => '新闻',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '1',
    'description' => '新闻模型搜索',
  ),
  5 => 
  array (
    'typeid' => '3',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '3',
    'name' => '图片',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '2',
    'description' => '图片模型搜索',
  ),
  6 => 
  array (
    'typeid' => '2',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '2',
    'name' => '下载',
    'parentid' => '0',
    'typedir' => '',
    'url' => '',
    'template' => '',
    'listorder' => '3',
    'description' => '下载模型搜索',
  ),
  7 => 
  array (
    'typeid' => '52',
    'siteid' => '1',
    'module' => 'search',
    'modelid' => '0',
    'name' => '专题',
    'parentid' => '0',
    'typedir' => 'special',
    'url' => '',
    'template' => '',
    'listorder' => '4',
    'description' => '专题',
  ),
);
?>