<?php
return array (
  105 => 
  array (
    'id' => '105',
    'catid' => '80',
    'typeid' => '0',
    'title' => '2016广西首届汽车展览会开幕',
    'style' => '',
    'thumb' => '',
    'keywords' => '广西 展览会 首届',
    'description' => '2016广西首届汽车展览会开幕',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=80&id=105',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458029499',
    'updatetime' => '1458029521',
    'hitsid' => 'c-1-105',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  121 => 
  array (
    'id' => '121',
    'catid' => '84',
    'typeid' => '0',
    'title' => '这是展览展会的热点资讯测试五',
    'style' => '',
    'thumb' => '',
    'keywords' => '展会 热点 这是',
    'description' => '这是展览展会的热点资讯测试三',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=84&id=121',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458033268',
    'updatetime' => '1458033279',
    'hitsid' => 'c-1-121',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  120 => 
  array (
    'id' => '120',
    'catid' => '83',
    'typeid' => '0',
    'title' => '这是展览展会的热点资讯测试四',
    'style' => '',
    'thumb' => '',
    'keywords' => '展会 热点 这是',
    'description' => '这是展览展会的热点资讯测试三',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=83&id=120',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458033242',
    'updatetime' => '1458033257',
    'hitsid' => 'c-1-120',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  119 => 
  array (
    'id' => '119',
    'catid' => '82',
    'typeid' => '0',
    'title' => '这是展览展会的热点资讯测试三',
    'style' => '',
    'thumb' => '',
    'keywords' => '展会 热点 这是',
    'description' => '这是展览展会的热点资讯测试三',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=82&id=119',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458033217',
    'updatetime' => '1458033228',
    'hitsid' => 'c-1-119',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  118 => 
  array (
    'id' => '118',
    'catid' => '81',
    'typeid' => '0',
    'title' => '这是展览展会的热点资讯测试二',
    'style' => '',
    'thumb' => '',
    'keywords' => '展会 热点 这是',
    'description' => '这是展览展会的热点资讯测试一',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=81&id=118',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458033195',
    'updatetime' => '1458033209',
    'hitsid' => 'c-1-118',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  117 => 
  array (
    'id' => '117',
    'catid' => '80',
    'typeid' => '0',
    'title' => '这是展览展会的热点资讯测试一',
    'style' => '',
    'thumb' => '',
    'keywords' => '展会 热点 这是',
    'description' => '这是展览展会的热点资讯测试一',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=80&id=117',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458033143',
    'updatetime' => '1458033187',
    'hitsid' => 'c-1-117',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  116 => 
  array (
    'id' => '116',
    'catid' => '85',
    'typeid' => '0',
    'title' => '2016新型热能设备主题展 4月6日亮相国家会议中心',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324020400437.png',
    'keywords' => '热能 会议中心 国家',
    'description' => '2016新型热能设备主题展 4月6日亮相国家会议中心',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=85&id=116',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458029872',
    'updatetime' => '1458029890',
    'hitsid' => 'c-1-116',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  115 => 
  array (
    'id' => '115',
    'catid' => '85',
    'typeid' => '0',
    'title' => '四川省商务厅关于组织参加第四届中国（上海）国际技术进',
    'style' => '',
    'thumb' => '',
    'keywords' => '四川省 商务厅 第四届',
    'description' => '四川省商务厅关于组织参加第四届中国（上海）国际技术进出口交易会的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=85&id=115',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458029845',
    'updatetime' => '1458029870',
    'hitsid' => 'c-1-115',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  114 => 
  array (
    'id' => '114',
    'catid' => '84',
    'typeid' => '0',
    'title' => '2015北京世界食品博览会新闻发布会召开',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324024718997.jpg',
    'keywords' => '北京 新闻发布会 博览会',
    'description' => '2015北京世界食品博览会新闻发布会召开',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=84&id=114',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458029803',
    'updatetime' => '1458029826',
    'hitsid' => 'c-1-114',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>