<?php
return array (
  84 => 
  array (
    'id' => '84',
    'catid' => '54',
    'typeid' => '0',
    'title' => '参展技巧攻略：如何实现最佳宣传效果',
    'style' => '',
    'thumb' => '',
    'keywords' => '技巧攻略 效果',
    'description' => '参展技巧攻略：如何实现最佳宣传效果',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=84',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024791',
    'updatetime' => '1458025401',
    'hitsid' => 'c-1-84',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  80 => 
  array (
    'id' => '80',
    'catid' => '54',
    'typeid' => '0',
    'title' => '展台设计中传统模板与量身设计的利与弊',
    'style' => '',
    'thumb' => '',
    'keywords' => '展台设计 模板 传统',
    'description' => '展台设计中传统模板与量身设计的利与弊',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=80',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024585',
    'updatetime' => '1458024702',
    'hitsid' => 'c-1-80',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  81 => 
  array (
    'id' => '81',
    'catid' => '54',
    'typeid' => '0',
    'title' => '企业在选择展览会时务必确定目标',
    'style' => '',
    'thumb' => '',
    'keywords' => '展览会 目标 企业',
    'description' => '企业在选择展览会时务必确定目标',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=81',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024703',
    'updatetime' => '1458024734',
    'hitsid' => 'c-1-81',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  82 => 
  array (
    'id' => '82',
    'catid' => '54',
    'typeid' => '0',
    'title' => '参展商容易忽略的四个细节',
    'style' => '',
    'thumb' => '',
    'keywords' => '参展商 细节',
    'description' => '参展商容易忽略的四个细节',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=82',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024735',
    'updatetime' => '1458024760',
    'hitsid' => 'c-1-82',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  83 => 
  array (
    'id' => '83',
    'catid' => '54',
    'typeid' => '0',
    'title' => '维护会展知识产权 推动行业健康发展',
    'style' => '',
    'thumb' => '',
    'keywords' => '知识产权 行业',
    'description' => '维护会展知识产权 推动行业健康发展',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=83',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024761',
    'updatetime' => '1458024790',
    'hitsid' => 'c-1-83',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  85 => 
  array (
    'id' => '85',
    'catid' => '54',
    'typeid' => '0',
    'title' => '参展企业如何赢得更多客户',
    'style' => '',
    'thumb' => '',
    'keywords' => '赢得 客户 更多',
    'description' => '参展企业如何赢得更多客户',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=85',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024814',
    'updatetime' => '1458024840',
    'hitsid' => 'c-1-85',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  86 => 
  array (
    'id' => '86',
    'catid' => '54',
    'typeid' => '0',
    'title' => '参展广交会有窍门 防骗技巧全攻略',
    'style' => '',
    'thumb' => '',
    'keywords' => '全攻略 窍门 技巧',
    'description' => '参展广交会有窍门 防骗技巧全攻略',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=54&id=86',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458024842',
    'updatetime' => '1458024864',
    'hitsid' => 'c-1-86',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>