<?php
return array (
  22 => 
  array (
    'id' => '22',
    'catid' => '28',
    'typeid' => '0',
    'title' => '外贸企业申报流程',
    'style' => '',
    'thumb' => '',
    'keywords' => '流程 外贸 企业',
    'description' => '外贸企业申报流程',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=28&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457936640',
    'updatetime' => '1457936715',
    'hitsid' => 'c-1-22',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '28',
    'typeid' => '0',
    'title' => '出口货物已视同内销征税备案表',
    'style' => '',
    'thumb' => '',
    'keywords' => '货物',
    'description' => '出口货物已视同内销征税备案表',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=28&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457936716',
    'updatetime' => '1457936738',
    'hitsid' => 'c-1-23',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>