<?php
return array (
  75 => 
  array (
    'id' => '75',
    'catid' => '89',
    'typeid' => '0',
    'title' => '展会展览--首页的境内场馆的测试内容一',
    'style' => '',
    'thumb' => '',
    'keywords' => '场馆 首页 展会',
    'description' => '展会展览--首页的境内场馆的测试内容一',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=89&id=75',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458023421',
    'updatetime' => '1458023466',
    'hitsid' => 'c-1-75',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  76 => 
  array (
    'id' => '76',
    'catid' => '89',
    'typeid' => '0',
    'title' => '展会展览--首页的境内场馆的测试内容二',
    'style' => '',
    'thumb' => '',
    'keywords' => '场馆 首页 展会',
    'description' => '展会展览--首页的境内场馆的测试内容一',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=89&id=76',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458023468',
    'updatetime' => '1458023479',
    'hitsid' => 'c-1-76',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  77 => 
  array (
    'id' => '77',
    'catid' => '89',
    'typeid' => '0',
    'title' => '展会展览--首页的境内场馆的测试内容三',
    'style' => '',
    'thumb' => '',
    'keywords' => '场馆 首页 展会',
    'description' => '展会展览--首页的境内场馆的测试内容一',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=89&id=77',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458023480',
    'updatetime' => '1458023494',
    'hitsid' => 'c-1-77',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  78 => 
  array (
    'id' => '78',
    'catid' => '89',
    'typeid' => '0',
    'title' => '展会展览--首页的境内场馆的测试内容四',
    'style' => '',
    'thumb' => '',
    'keywords' => '场馆 首页 展会',
    'description' => '展会展览--首页的境内场馆的测试内容一',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=89&id=78',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458023496',
    'updatetime' => '1458023508',
    'hitsid' => 'c-1-78',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  79 => 
  array (
    'id' => '79',
    'catid' => '89',
    'typeid' => '0',
    'title' => '展会展览--首页的境内场馆的测试内容五',
    'style' => '',
    'thumb' => '',
    'keywords' => '场馆 首页 展会',
    'description' => '展会展览--首页的境内场馆的测试内容五',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=89&id=79',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458023510',
    'updatetime' => '1458023530',
    'hitsid' => 'c-1-79',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>