<?php
return array (
  42 => 
  array (
    'id' => '42',
    'catid' => '63',
    'typeid' => '0',
    'title' => '四川省商务厅关于开展2015年省级电子商务示范基地、示范企',
    'style' => '',
    'thumb' => '',
    'keywords' => '四川省 商务厅 示范基地',
    'description' => '四川省商务厅关于开展2015年省级电子商务示范基地、示范企业申报创建工作的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=63&id=42',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949988',
    'updatetime' => '1457950022',
    'hitsid' => 'c-1-42',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  43 => 
  array (
    'id' => '43',
    'catid' => '63',
    'typeid' => '0',
    'title' => '关于做好2013年度进口贴息资金申报工作的预通知',
    'style' => '',
    'thumb' => '',
    'keywords' => '贴息 资金 年度',
    'description' => '关于做好2013年度进口贴息资金申报工作的预通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=63&id=43',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457950024',
    'updatetime' => '1457950045',
    'hitsid' => 'c-1-43',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  44 => 
  array (
    'id' => '44',
    'catid' => '63',
    'typeid' => '0',
    'title' => '成都市商务局成都市财政局关于办理2012年度中小企业国际市',
    'style' => '',
    'thumb' => '',
    'keywords' => '成都市 商务局 财政局',
    'description' => '成都市商务局成都市财政局关于办理2012年度中小企业国际市场开拓资金审核拨付有关问题的通',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=63&id=44',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457950047',
    'updatetime' => '1457950078',
    'hitsid' => 'c-1-44',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>