<?php
return array (
  48 => 
  array (
    'id' => '48',
    'catid' => '67',
    'typeid' => '0',
    'title' => '今年将开展扶助小微企业专项行动',
    'style' => '',
    'thumb' => '',
    'keywords' => '专项 企业',
    'description' => '今年将开展扶助小微企业专项行动',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=67&id=48',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457951965',
    'updatetime' => '1457951992',
    'hitsid' => 'c-1-48',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  61 => 
  array (
    'id' => '61',
    'catid' => '67',
    'typeid' => '0',
    'title' => '政策法规-扶持政策-其他--测试（重要扶持政策推荐测试）',
    'style' => '',
    'thumb' => '',
    'keywords' => '政策 政策法规',
    'description' => '政策法规-扶持政策-其他--测试（重要扶持政策推荐测试）',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=67&id=61',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458008117',
    'updatetime' => '1458008193',
    'hitsid' => 'c-1-61',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>