<?php
return array (
  54 => 
  array (
    'id' => '54',
    'catid' => '71',
    'typeid' => '0',
    'title' => '国际要闻第一条内容的测试开始开始开始开始开始开始',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0314/20160314080054616.jpg',
    'keywords' => '要闻 内容 国际',
    'description' => '国际要闻第一条内容的测试开始',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=71&id=54',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457956812',
    'updatetime' => '1457956862',
    'hitsid' => 'c-1-54',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  55 => 
  array (
    'id' => '55',
    'catid' => '71',
    'typeid' => '0',
    'title' => '国际要闻第二条内容的测试开始开始开始',
    'style' => '',
    'thumb' => '',
    'keywords' => '要闻 内容 国际',
    'description' => '国际要闻第二条内容的测试开始国际要闻第二条内容的测试开始',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=71&id=55',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457956863',
    'updatetime' => '1457956876',
    'hitsid' => 'c-1-55',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>