<?php
return array (
  24 => 
  array (
    'id' => '24',
    'catid' => '57',
    'typeid' => '0',
    'title' => '商务部 海关总署公告2015第59号 关于调整加工贸易禁止类商品',
    'style' => '',
    'thumb' => '',
    'keywords' => '海关总署 商务部 加工贸易',
    'description' => '商务部 海关总署公告2015第59号 关于调整加工贸易禁止类商品目录的公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=57&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457946178',
    'updatetime' => '1457946205',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '57',
    'typeid' => '0',
    'title' => '联合公告2015年第69号(关于落实《中华人民共和国固体废物污',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0314/20160314050504344.jpg',
    'keywords' => '固体 废物 中华人民共和国',
    'description' => '联合公告2015年第69号(关于落实《中华人民共和国固体废物污染环境防治法》第二十五条修订内',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=57&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457946207',
    'updatetime' => '1457946312',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  26 => 
  array (
    'id' => '26',
    'catid' => '57',
    'typeid' => '0',
    'title' => '联合公告2015年第69号(关于落实《中华人民共和国固体废物污',
    'style' => '',
    'thumb' => '',
    'keywords' => '固体 废物 中华人民共和国',
    'description' => '联合公告2015年第69号(关于落实《中华人民共和国固体废物污染环境防治法》第二十五条修订内',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=57&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457946314',
    'updatetime' => '1457946547',
    'hitsid' => 'c-1-26',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  27 => 
  array (
    'id' => '27',
    'catid' => '57',
    'typeid' => '0',
    'title' => '商务部公告2015年第52号 公布《2016年原油非国营贸易进口允许',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324024813441.jpg',
    'keywords' => '商务部 原油 年第',
    'description' => '商务部公告2015年第52号 公布《2016年原油非国营贸易进口允许量总量、申请条件和申请程序》',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=57&id=27',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457946548',
    'updatetime' => '1457946576',
    'hitsid' => 'c-1-27',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  28 => 
  array (
    'id' => '28',
    'catid' => '57',
    'typeid' => '0',
    'title' => '商务部公告2015年第51号 公布《2016年化肥进口关税配额总量、',
    'style' => '',
    'thumb' => '',
    'keywords' => '商务部 配额 关税',
    'description' => '商务部公告2015年第51号 公布《2016年化肥进口关税配额总量、分配原则及相关程序》',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=57&id=28',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457946577',
    'updatetime' => '1457946608',
    'hitsid' => 'c-1-28',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>