<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '25',
    'typeid' => '0',
    'title' => '外贸公共服务平台关于出口退税预审系统维护的公告',
    'style' => '',
    'thumb' => '',
    'keywords' => '公共服务 出口退税 外贸',
    'description' => '外贸公共服务平台关于出口退税预审系统维护的公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457933637',
    'updatetime' => '1457933681',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '25',
    'typeid' => '0',
    'title' => '国家税务总局关于发布 出口退税率文库2016A版的通知',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324025556942.jpg',
    'keywords' => '国家税务总局 退税率 文库',
    'description' => '国家税务总局关于发布 出口退税率文库2016A版的通知',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457933979',
    'updatetime' => '1457934013',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '25',
    'typeid' => '0',
    'title' => '最新出口退税申报系统补丁sp2升级通知',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324025725981.jpg',
    'keywords' => '出口退税 补丁 系统',
    'description' => '最新出口退税申报系统补丁sp2升级通知',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934015',
    'updatetime' => '1457934047',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '25',
    'typeid' => '0',
    'title' => '最新出口退税申报系统补丁sp1升级通知',
    'style' => '',
    'thumb' => '',
    'keywords' => '出口退税 补丁 系统',
    'description' => '最新出口退税申报系统补丁sp1升级通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934049',
    'updatetime' => '1457934075',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '25',
    'typeid' => '0',
    'title' => '最新出口退税申报系统补丁sp1升级通知',
    'style' => '',
    'thumb' => '',
    'keywords' => '出口退税 补丁 系统',
    'description' => '最新出口退税申报系统补丁sp1升级通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934077',
    'updatetime' => '1457934103',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '25',
    'typeid' => '0',
    'title' => '最新出口退税申报系统升级通知（生产企业出口退税申报系',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324022947401.jpg',
    'keywords' => '出口退税 系统 企业',
    'description' => '最新出口退税申报系统升级通知（生产企业出口退税申报系统V15 0版、外贸企业出口退税申报系统V17 0版）',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934104',
    'updatetime' => '1457934136',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '25',
    'typeid' => '0',
    'title' => '成都市国家税务局关于金税三期工程省级应用集中优化版切',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0324/20160324025259210.jpg',
    'keywords' => '国家税务局 金税 成都市',
    'description' => '成都市国家税务局关于金税三期工程省级应用集中优化版切换期间暂停出口退税业务办理的通知',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934138',
    'updatetime' => '1457934168',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '25',
    'typeid' => '0',
    'title' => '最新出口退税申报系统升级通知（生产企业14.20版，外贸企业',
    'style' => '',
    'thumb' => '',
    'keywords' => '企业 出口退税 外贸',
    'description' => '最新出口退税申报系统升级通知（生产企业14 20版，外贸企业16 20版）',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=25&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457934169',
    'updatetime' => '1457934192',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>