<?php
return array (
  95 => 
  array (
    'id' => '95',
    'catid' => '18',
    'typeid' => '0',
    'title' => '上海慧展广告有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315033927615.jpg',
    'keywords' => '上海 广告 有限公司',
    'description' => '上海慧展广告有限公司',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=95',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027535',
    'updatetime' => '1458028434',
    'hitsid' => 'c-1-95',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  100 => 
  array (
    'id' => '100',
    'catid' => '18',
    'typeid' => '0',
    'title' => '成都国腾展览策划有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315034237174.jpg',
    'keywords' => '成都 有限公司',
    'description' => '成都国腾展览策划有限公司',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=100',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027727',
    'updatetime' => '1458027763',
    'hitsid' => 'c-1-100',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  98 => 
  array (
    'id' => '98',
    'catid' => '18',
    'typeid' => '0',
    'title' => '双流嘉盛展览展示制作厂',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315034127852.jpg',
    'keywords' => '双流 制作厂 展览展示',
    'description' => '双流县嘉盛展览展示制作厂是一家专业从事：展览、展示、展厅、会议、专柜等特装工程制作与搭建、展期维护的企业。　　我们现有制作工厂面积   ',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=98',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027665',
    'updatetime' => '1458027697',
    'hitsid' => 'c-1-98',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  97 => 
  array (
    'id' => '97',
    'catid' => '18',
    'typeid' => '0',
    'title' => '金字塔（上海）展览展示工程有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315034056629.jpg',
    'keywords' => '展览展示 上海 金字塔',
    'description' => '金字塔（上海）展览展示工程有限公司',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=97',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027613',
    'updatetime' => '1458027664',
    'hitsid' => 'c-1-97',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  96 => 
  array (
    'id' => '96',
    'catid' => '18',
    'typeid' => '0',
    'title' => '上海仕博文化传播有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315034008387.jpg',
    'keywords' => '上海 文化传播 有限公司',
    'description' => '上海仕博文化传播有限公司',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=96',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027573',
    'updatetime' => '1458027611',
    'hitsid' => 'c-1-96',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  94 => 
  array (
    'id' => '94',
    'catid' => '18',
    'typeid' => '0',
    'title' => '广州市正点礼仪服务有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315033837719.jpg',
    'keywords' => '礼仪服务 广州市 有限公司',
    'description' => '广州市正点礼仪服务有限公司',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=94',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027447',
    'updatetime' => '1458027533',
    'hitsid' => 'c-1-94',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  104 => 
  array (
    'id' => '104',
    'catid' => '18',
    'typeid' => '0',
    'title' => '广州市保利锦汉展览有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315034538283.jpg',
    'keywords' => '锦汉 保利 广州市',
    'description' => '广州市保利锦汉展览有限公司',
    'posids' => '1',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=104',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027897',
    'updatetime' => '1458027942',
    'hitsid' => 'c-1-104',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  103 => 
  array (
    'id' => '103',
    'catid' => '18',
    'typeid' => '0',
    'title' => '山东国际博览中心有限公司',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0315/20160315034452828.jpg',
    'keywords' => '山东 国际 有限公司',
    'description' => '山东国际博览中心有限公司',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=18&id=103',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458027853',
    'updatetime' => '1458027895',
    'hitsid' => 'c-1-103',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>