<?php
return array (
  50 => 
  array (
    'id' => '50',
    'catid' => '70',
    'typeid' => '0',
    'title' => '这是测试国内新闻一的例子',
    'style' => '',
    'thumb' => 'http://www.swt.com/uploadfile/2016/0314/20160314073931714.jpg',
    'keywords' => '例子 这是 新闻',
    'description' => '这是测试国内新闻一的例子',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=70&id=50',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457955540',
    'updatetime' => '1457955576',
    'hitsid' => 'c-1-50',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  51 => 
  array (
    'id' => '51',
    'catid' => '70',
    'typeid' => '0',
    'title' => '这是第二条国内新闻的测试标题结果',
    'style' => '',
    'thumb' => '',
    'keywords' => '标题 结果 这是',
    'description' => '这是第二条国内新闻的测试标题结果',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=70&id=51',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457956078',
    'updatetime' => '1457956117',
    'hitsid' => 'c-1-51',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>