<?php
return array (
  29 => 
  array (
    'id' => '29',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家税务总局关于取消销货退回消费税退税等两项消费税审',
    'style' => '',
    'thumb' => '',
    'keywords' => '消费税 国家税务总局',
    'description' => '国家税务总局关于取消销货退回消费税退税等两项消费税审批事项后有关管理问题的公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=29',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457948969',
    'updatetime' => '1457949001',
    'hitsid' => 'c-1-29',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  39 => 
  array (
    'id' => '39',
    'catid' => '58',
    'typeid' => '0',
    'title' => '中华人民共和国海关总署 国家外汇管理局公',
    'style' => '',
    'thumb' => '',
    'keywords' => '国家外汇管理局 海关总署 中',
    'description' => '中华人民共和国海关总署 国家外汇管理局公',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=39',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949653',
    'updatetime' => '1457949680',
    'hitsid' => 'c-1-39',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  38 => 
  array (
    'id' => '38',
    'catid' => '58',
    'typeid' => '0',
    'title' => '外汇管理局关于完善银行贸易融资业务外汇管理有关问题的',
    'style' => '',
    'thumb' => '',
    'keywords' => '外汇管理局 外汇 业务',
    'description' => '外汇管理局关于完善银行贸易融资业务外汇管理有关问题的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=38',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949626',
    'updatetime' => '1457949651',
    'hitsid' => 'c-1-38',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家外汇管理局关于调整人民币外汇衍生产品业务管理的通',
    'style' => '',
    'thumb' => '',
    'keywords' => '国家外汇管理局 业务管理',
    'description' => '国家外汇管理局关于调整人民币外汇衍生产品业务管理的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=37',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949592',
    'updatetime' => '1457949625',
    'hitsid' => 'c-1-37',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '58',
    'typeid' => '0',
    'title' => '商务部、财政部令2014年第2号 《对外劳务合作风险处置备用',
    'style' => '',
    'thumb' => '',
    'keywords' => '财政部 商务部 劳务合作',
    'description' => '商务部、财政部令2014年第2号 《对外劳务合作风险处置备用金管理办法（试行）》',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=36',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949569',
    'updatetime' => '1457949590',
    'hitsid' => 'c-1-36',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  35 => 
  array (
    'id' => '35',
    'catid' => '58',
    'typeid' => '0',
    'title' => ' 为加快外汇市场发展，推动市场对外开',
    'style' => '',
    'thumb' => '',
    'keywords' => '外汇市场 对外开放 外汇',
    'description' => '中国人民银行 国家外汇管理局公告〔2015〕第40号',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=35',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949116',
    'updatetime' => '1457949567',
    'hitsid' => 'c-1-35',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '58',
    'typeid' => '0',
    'title' => '《2015年食糖进口关税配额申请和分配细则》',
    'style' => '',
    'thumb' => '',
    'keywords' => '食糖 配额 关税',
    'description' => '《2015年食糖进口关税配额申请和分配细则》',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949094',
    'updatetime' => '1457949115',
    'hitsid' => 'c-1-34',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家税务总局 关于出口企业申报出口退（免）税免予提供纸',
    'style' => '',
    'thumb' => '',
    'keywords' => '国家税务总局 企业',
    'description' => '国家税务总局 关于出口企业申报出口退（免）税免予提供纸质出口货物报关单的公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=33',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949072',
    'updatetime' => '1457949092',
    'hitsid' => 'c-1-33',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家税务总局关于《适用增值税零税率应税服务退（免）税',
    'style' => '',
    'thumb' => '',
    'keywords' => '零税率 国家税务总局 增值税',
    'description' => '国家税务总局关于《适用增值税零税率应税服务退（免）税管理办法》的补充公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949046',
    'updatetime' => '1457949070',
    'hitsid' => 'c-1-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  31 => 
  array (
    'id' => '31',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家税务总局关于发布《市场采购贸易方式出口货物免税管',
    'style' => '',
    'thumb' => '',
    'keywords' => '税管 国家税务总局 货物',
    'description' => '国家税务总局关于发布《市场采购贸易方式出口货物免税管理办法（试行）》的公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=31',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949025',
    'updatetime' => '1457949045',
    'hitsid' => 'c-1-31',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  30 => 
  array (
    'id' => '30',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家税务总局关于发布影视等出口服务编码及2015A版出口退税',
    'style' => '',
    'thumb' => '',
    'keywords' => '国家税务总局 出口退税 编码',
    'description' => '国家税务总局关于发布影视等出口服务编码及2015A版出口退税率文库（升级包）的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=30',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949002',
    'updatetime' => '1457949023',
    'hitsid' => 'c-1-30',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>