<?php
return array (
  89 => 
  array (
    'id' => '89',
    'catid' => '90',
    'typeid' => '0',
    'title' => '阿德莱德会议中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '阿德莱德 会议中心',
    'description' => '阿德莱德会议中心',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=90&id=89',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458026748',
    'updatetime' => '1458026771',
    'hitsid' => 'c-1-89',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  90 => 
  array (
    'id' => '90',
    'catid' => '90',
    'typeid' => '0',
    'title' => '波多黎各会议中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '波多黎各 会议中心',
    'description' => '波多黎各会议中心',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=90&id=90',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458026772',
    'updatetime' => '1458026796',
    'hitsid' => 'c-1-90',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  91 => 
  array (
    'id' => '91',
    'catid' => '90',
    'typeid' => '0',
    'title' => '毕尔巴鄂展览中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '毕尔巴鄂 展览中心',
    'description' => '毕尔巴鄂展览中心',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=90&id=91',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458026797',
    'updatetime' => '1458026826',
    'hitsid' => 'c-1-91',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  92 => 
  array (
    'id' => '92',
    'catid' => '90',
    'typeid' => '0',
    'title' => '阿德莱德会议中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '阿德莱德 会议中心',
    'description' => '阿德莱德会议中心',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=90&id=92',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458026827',
    'updatetime' => '1458026864',
    'hitsid' => 'c-1-92',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  93 => 
  array (
    'id' => '93',
    'catid' => '90',
    'typeid' => '0',
    'title' => '赫尔辛基展览中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '赫尔辛基 展览中心',
    'description' => '赫尔辛基展览中心',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=90&id=93',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458026866',
    'updatetime' => '1458026888',
    'hitsid' => 'c-1-93',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>