<?php
return array (
  24 => 
  array (
    'id' => '24',
    'catid' => '57',
    'typeid' => '0',
    'title' => '商务部 海关总署公告2015第59号 关于调整加工贸易禁止类商品',
    'style' => '',
    'thumb' => '',
    'keywords' => '海关总署 商务部 加工贸易',
    'description' => '商务部 海关总署公告2015第59号 关于调整加工贸易禁止类商品目录的公告',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=57&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457946178',
    'updatetime' => '1457946205',
    'hitsid' => 'c-1-24',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  36 => 
  array (
    'id' => '36',
    'catid' => '58',
    'typeid' => '0',
    'title' => '商务部、财政部令2014年第2号 《对外劳务合作风险处置备用',
    'style' => '',
    'thumb' => '',
    'keywords' => '财政部 商务部 劳务合作',
    'description' => '商务部、财政部令2014年第2号 《对外劳务合作风险处置备用金管理办法（试行）》',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=36',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949569',
    'updatetime' => '1457949590',
    'hitsid' => 'c-1-36',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  37 => 
  array (
    'id' => '37',
    'catid' => '58',
    'typeid' => '0',
    'title' => '国家外汇管理局关于调整人民币外汇衍生产品业务管理的通',
    'style' => '',
    'thumb' => '',
    'keywords' => '国家外汇管理局 业务管理',
    'description' => '国家外汇管理局关于调整人民币外汇衍生产品业务管理的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=37',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949592',
    'updatetime' => '1457949625',
    'hitsid' => 'c-1-37',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  38 => 
  array (
    'id' => '38',
    'catid' => '58',
    'typeid' => '0',
    'title' => '外汇管理局关于完善银行贸易融资业务外汇管理有关问题的',
    'style' => '',
    'thumb' => '',
    'keywords' => '外汇管理局 外汇 业务',
    'description' => '外汇管理局关于完善银行贸易融资业务外汇管理有关问题的通知',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=38',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949626',
    'updatetime' => '1457949651',
    'hitsid' => 'c-1-38',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  39 => 
  array (
    'id' => '39',
    'catid' => '58',
    'typeid' => '0',
    'title' => '中华人民共和国海关总署 国家外汇管理局公',
    'style' => '',
    'thumb' => '',
    'keywords' => '国家外汇管理局 海关总署 中',
    'description' => '中华人民共和国海关总署 国家外汇管理局公',
    'posids' => '0',
    'url' => 'http://www.swt.com/index.php?m=content&c=index&a=show&catid=58&id=39',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1457949653',
    'updatetime' => '1457949680',
    'hitsid' => 'c-1-39',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>